# Generated by Django 3.0.5 on 2020-08-23 08:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('star_ratings', '0003_auto_20160721_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='userrating',
            options={'verbose_name': 'User Rating', 'verbose_name_plural': 'User Ratings'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='average',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6, verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='star_ratings.Rating', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
